### PR TITLE
Fixes #1336 Bootstrap for SLES 15 

### LINKED ISSUE #1336: Bootstrap for SUSE 15 needs updated
### Description of Issue/Question
If I try to install Salt on SLES 15 using the option on the website titled "Bootstrap - Multi-Platform", I get the following error:
"awk: fatal: cannot open file `/etc/SuSE-release' for reading (No such file or directory)"

This error occurs because as of SLES 15, /etc/SuSE-release has been removed in favor of /etc/os-release.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
try to run the bootstrap script to install Salt on SUSE Leap 15.

### Versions Report
Unable to provide since Salt is not installed.

SUSE Leap 15.

### PR DESCRIPTION
**Pull request by max298**
### What does this PR do?
Adds bootstrapping for SuSE Linux Enterprise 15 SP1

### What issues does this PR fix or reference?
#1336 

### Previous Behavior
Bootstrapping on SLES 15 SP1 failed

### New Behavior
Bootstrapping on SLES 15 SP1 works as expected

### CODE REVIEW

File: bootstrap-salt.sh [hunk 1]
```diff
@@ -6578,6 +6586,108 @@ install_opensuse_15_git() {
...
+    if [ "${_EXTRA_PACKAGES}" != "" ]; then
+        echoinfo "Installing the following extra packages as requested: ${_EXTRA_PACKAGES}"
+        # shellcheck disable=SC2086
+        __zypper_install ${_EXTRA_PACKAGES} || return 1
+    fi
+
+    return 0
+}
+
+install_suse_15_git_deps() {
```
Comment (s0undt3ch) [inline bootstrap-salt.sh:6600]: Why are you not calling the opensuse git deps function?
I had to fix that one in order to properly install Neon, which needs to be pip installed because we defaulted to setuptools.
Are you sure this really works?

Comment (max298) [reply bootstrap-salt.sh:6600]: You are right, this wasn't quite working. I'm now calling the opensuse git deps function, which is working fine using freshly deployed systems.

File: bootstrap-salt.sh [hunk 2]
```diff
@@ -6342,7 +6350,7 @@ install_opensuse_stable() {
 }
 
 install_opensuse_git() {
-
+
```
Comment (vutny) [inline bootstrap-salt.sh]: This is a minor catch. I don't think we need any blank lines here, with trailing blanks especially.

**Review by vutny — COMMENTED** [review]
Looks good to me in general, thanks.

**Review by s0undt3ch — APPROVED** [review]
