### PR TITLE
Tornado fix

### LINKED ISSUE #1521: Boostrap ok, but salt-minion failing on freebsd 11.4 (no py37-tornado4)
### Description of Issue/Question

Salt bootstrap doesn't install python-tornado  

### Setup
just new freebsd instance

### Steps to Reproduce Issue
I run it with kitchen with:
```
       salt_install = bootstrap
       salt_url = https://raw.githubusercontent.com/saltstack/salt-bootstrap/5e9e43109d9e8773c0dea1169b167bb244e2a488/bootstrap-salt.sh
       bootstrap_options = -x python3 -X git v2019.2.5
       salt_version = 2019.2.5
```
boostrap is installed all right but salt-minion failing with:
```
root@kitchen:~ # bash /tmp/kitchen/bootstrap.sh -x python3 -X git v2019.2.5
.....blebleble...
       copying doc/man/salt-unity.1 -> /usr/local/share/man/man1
       creating /usr/local/share/man/man7
       copying doc/man/salt.7 -> /usr/local/share/man/man7
       running install_egg_info
       Writing /usr/local/lib/python3.7/site-packages/salt-2019.2.5-py3.7.egg-info
        *  INFO: Running install_freebsd_git_post()
       salt_minion_enable:  -> YES
        *  INFO: Salt installed!
root@kitchen:~ # echo $?
0
root@kitchen:~ # salt-minion
Traceback (most recent call last):
  File "/usr/local/bin/salt-minion", line 26, in <module>
    salt_minion()
  File "/usr/local/lib/python3.7/site-packages/salt/scripts.py", line 181, in salt_minion
    import salt.utils.process
  File "/usr/local/lib/python3.7/site-packages/salt/utils/process.py", line 37, in <module>
    from tornado import gen
ModuleNotFoundError: No module named 'tornado'
```
### Versions and Systems
master bootstrap
11.4-RELEASE-p5

### PR DESCRIPTION
**Pull request by marek-knappe**
### What does this PR do?
Fixing issue with tornado on freebsd

### What issues does this PR fix or reference?
Fixes #1521 

### Previous Behavior
Not working on freebsd 11.4

### New Behavior
working on freebsd 11.4

### CODE REVIEW

File: bootstrap-salt.sh [hunk 1]
```diff
@@ -5835,6 +5835,8 @@ install_freebsd_git_deps() {
         /usr/local/sbin/pkg install -y ${SALT_DEPENDENCIES} python || return 1
 
         /usr/local/sbin/pkg install -y py37-requests || return 1
+        /usr/local/sbin/pkg install -y www/py-tornado4 || return 1
```
Comment (krionbsd) [inline bootstrap-salt.sh]: I think you mean `py37-tornado4` here, there's no package `www/py-tornado4`

**Review by krionbsd — CHANGES_REQUESTED** [review]

File: bootstrap-salt.sh (hunk 1 above)
Comment (marek-knappe) [reply bootstrap-salt.sh]: Imho installing it as www/py-tornado4 is a bit safer way as if they change python to py38 it will still work 

```
root@fbsd114:~ # pkg info www/py-tornado4
py37-tornado4-4.5.3
Name           : py37-tornado4
Version        : 4.5.3
Installed on   : Thu Oct  8 13:08:13 2020 PDT
Origin         : www/py-tornado4
```

```
root@kitchen:~ #  pkg install -y www/py-tornado4
Updating FreeBSD repository catalogue...
FreeBSD repository is up to date.
All repositories are up to date.
The following 1 package(s) will be affected (of 0 checked):

New packages to be INSTALLED:
	py37-tornado4: 4.5.3

Number of packages to be installed: 1

The process will require 4 MiB more space.
588 KiB to be downloaded.
[1/1] Fetching py37-tornado4-4.5.3.txz: 100%  588 KiB 602.1kB/s    00:01
Checking integrity... done (0 conflicting)
[1/1] Installing py37-tornado4-4.5.3...
[1/1] Extracting py37-tornado4-4.5.3: 100%
root@kitchen:~ #
```

Comment (krionbsd) [reply bootstrap-salt.sh]: That might be the case, but we should test it first before importing into bootstrap so it's better to hardcode python versions and upgrade only after careful testing.

**Review by krionbsd — CHANGES_REQUESTED** [review]
As I mentioned already, let's use exact python versioned packages as it adds less failure points in the future

File: bootstrap-salt.sh (hunk 1 above)
Comment (marek-knappe) [reply bootstrap-salt.sh]: "Upgrade after careful testing" :))) Are u aware that we are talking here about Freebsd which is not tested in salt even not carefully ;) Anyway, changed :) Thanks for input

Comment (krionbsd) [reply bootstrap-salt.sh]: That's not true, FreeBSD is covered by tests and being tested by CI with every merge.

**Review by krionbsd — APPROVED** [review]
