### PR TITLE
Debugging build failures on Arch, Fedora and Tumbleweed

### LINKED ISSUE #2017: Builds failing on Arch, Fedora and Tumbleweed
### Description of Issue/Question

Current clean build is failing to build on Arch and Fedora due to rust_openssl and Py 3.12, this could be due to latest updates to openssl and it's Rust libaries
```
 9967 2024-09-17T19:30:13.5845214Z        Traceback (most recent call last):
 9968 2024-09-17T19:30:13.5846145Z          File "/usr/bin/salt-call", line 8, in <module>
 9969 2024-09-17T19:30:13.5846601Z            sys.exit(salt_call())
 9970 2024-09-17T19:30:13.5846898Z              ^^^^^^^^^^^
 9971 2024-09-17T19:30:13.5847490Z          File "/usr/lib/python3.12/site-packages/salt/scripts.py", line 435, in salt_call
 9972 2024-09-17T19:30:13.5848019Z            import salt.cli.call
 9973 2024-09-17T19:30:13.5848589Z          File "/usr/lib/python3.12/site-packages/salt/cli/call.py", line 3, in <module>
 9974 2024-09-17T19:30:13.5849389Z            import salt.cli.caller
 9975 2024-09-17T19:30:13.5849985Z          File "/usr/lib/python3.12/site-packages/salt/cli/caller.py", line 12, in <module>
 9976 2024-09-17T19:30:13.5850508Z            import salt.channel.client
 9977 2024-09-17T19:30:13.5851135Z          File "/usr/lib/python3.12/site-packages/salt/channel/client.py", line 15, in <module>
 9978 2024-09-17T19:30:13.5851665Z            import salt.crypt
 9979 2024-09-17T19:30:13.5852215Z          File "/usr/lib/python3.12/site-packages/salt/crypt.py", line 51, in <module>
 9980 2024-09-17T19:30:13.5853026Z            from cryptography.hazmat.primitives import hashes, serialization
 9981 2024-09-17T19:30:13.5853981Z          File "/usr/lib/python3.12/site-packages/cryptography/hazmat/primitives/serialization/__init__.py", line 25, in <module>
 9982 2024-09-17T19:30:13.5854834Z            from cryptography.hazmat.primitives.serialization.ssh import (
 9983 2024-09-17T19:30:13.5855769Z          File "/usr/lib/python3.12/site-packages/cryptography/hazmat/primitives/serialization/ssh.py", line 27, in <module>
 9984 2024-09-17T19:30:13.5856536Z            from cryptography.hazmat.primitives.ciphers import (
 9985 2024-09-17T19:30:13.5857401Z          File "/usr/lib/python3.12/site-packages/cryptography/hazmat/primitives/ciphers/__init__.py", line 11, in <module>
 9986 2024-09-17T19:30:13.5858190Z            from cryptography.hazmat.primitives.ciphers.base import (
 9987 2024-09-17T19:30:13.5859062Z          File "/usr/lib/python3.12/site-packages/cryptography/hazmat/primitives/ciphers/base.py", line 143, in <module>
 9988 2024-09-17T19:30:13.5859839Z            CipherContext.register(rust_openssl.ciphers.CipherContext)
 9989 2024-09-17T19:30:13.5860292Z                            ^^^^^^^^^^^^^^^^^^^^
 9990 2024-09-17T19:30:13.5860797Z        AttributeError: module 'openssl' has no attribute 'ciphers'
 9991 2024-09-17T19:30:13.6104892Z        No salt-minion installed, install must have failed!!
 9992 2024-09-17T19:30:13.6105614Z        salt_install = bootstrap
```

Tumbleweed is due to other issues
```
4800 2024-09-17T19:28:52.1566419Z         File "<string>", line 2, in <module>
4801 2024-09-17T19:28:52.1567664Z         File "<pip-setuptools-caller>", line 34, in <module> 
4802 2024-09-17T19:28:52.1573287Z         File "/tmp/pip-download-behx8359/contextvars_39230551c4334e4281ac09382e35f941/setup.py", line 9, in <module>
4803 2024-09-17T19:28:52.1575298Z           setuptools.setup(
4804 2024-09-17T19:28:52.1576316Z         File "/usr/lib/python3.12/site-packages/setuptools/__init__.py", line 117, in setup
4805 2024-09-17T19:28:52.1577294Z           return distutils.core.setup(**attrs)
4806 2024-09-17T19:28:52.1577894Z                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
4807 2024-09-17T19:28:52.1578634Z         File "/usr/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 145, in setup
4808 2024-09-17T19:28:52.1579238Z           _setup_distribution = dist = klass(attrs)
4809 2024-09-17T19:28:52.1579914Z                                        ^^^^^^^^^^^^
4810 2024-09-17T19:28:52.1580557Z         File "/usr/lib/python3.12/site-packages/setuptools/dist.py", line 283, in __init__
4811 2024-09-17T19:28:52.1581142Z           _Distribution.__init__(self, dist_attrs)
4812 2024-09-17T19:28:52.1581867Z         File "/usr/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 279, in __init__
4813 2024-09-17T19:28:52.1582450Z           self.finalize_options()
4814 2024-09-17T19:28:52.1583092Z         File "/usr/lib/python3.12/site-packages/setuptools/dist.py", line 635, in finalize_options
4815 2024-09-17T19:28:52.1583634Z           ep(self)
4816 2024-09-17T19:28:52.1584267Z         File "/usr/lib/python3.12/site-packages/setuptools/dist.py", line 655, in _finalize_setup_keywords
4817 2024-09-17T19:28:52.1584876Z           ep.load()(self, ep.name, value) 
4818 2024-09-17T19:28:52.1585191Z           ^^^^^^^^^
4819 2024-09-17T19:28:52.1585636Z         File "/usr/lib64/python3.12/importlib/metadata/__init__.py", line 207, in load
4820 2024-09-17T19:28:52.1586207Z           return functools.reduce(getattr, attrs, module)
4821 2024-09-17T19:28:52.1586610Z                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
4822 2024-09-17T19:28:52.1587196Z              AttributeError: module 'setuptools.dist' has no attribute 'check_test_suite'
4823 2024-09-17T19:28:52.1587700Z              [end of output]
4824 2024-09-17T19:28:52.1587963Z          
4825 2024-09-17T19:28:52.1588385Z          note: This error originates from a subprocess, and is likely not a problem with pip.
4826 2024-09-17T19:28:52.1588986Z        error: metadata-generation-failed
4827 2024-09-17T19:28:52.1589305Z          
4828 2024-09-17T19:28:52.1589881Z        × Encountered error while generating package metadata.
4829 2024-09-17T19:28:52.1590370Z        ╰─> See above for output.
4830 2024-09-17T19:28:52.1590659Z          
4831 2024-09-17T19:28:52.1590997Z        note: This is an issue with the package mentioned above, not pip.
4832 2024-09-17T19:28:52.1591461Z        hint: See above for details.
4833 2024-09-17T19:28:52.3449786Z        Failed to download salt dependencies
4834 2024-09-17T19:28:52.3453173Z         *  INFO: Installing Downloaded Salt Dependencies
4835 2024-09-17T19:28:52.3455860Z         * DEBUG: Running 'pip3.12 install  --ignore-installed --prefix=/usr /tmp/git/deps/*'
4836 2024-09-17T19:28:52.6669044Z        ERROR: Invalid requirement: '/tmp/git/deps/*'
4837 2024-09-17T19:28:52.6670231Z        Hint: It looks like a path. File '/tmp/git/deps/*' does not exist.
```

and directory ```/tmp/git/deps``` does exist, so why isn't it getting seen

### Setup
(Please provide relevant configs (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible, `bootstrap-salt.sh -D`.)

### Versions and Systems
(`salt --versions-report`, `bootstrap-salt.sh -v`, system type and version,
cloud/VM provider as appropriate.)

### PR DESCRIPTION
**Pull request by dmurphy18**
### What does this PR do?
Debugging build failures on Arch, Fedora and Tumbleweed

### What issues does this PR fix or reference?
Fixes https://github.com/saltstack/salt-bootstrap/issues/2017

### CODE REVIEW

File: bootstrap-salt.sh [hunk 1]
```diff
@@ -2102,10 +2103,15 @@ __git_clone_and_checkout() {
...
-                if git clone --depth 1 --branch "$GIT_REV" "$_SALT_REPO_URL" "$__SALT_CHECKOUT_REPONAME"; then
+                ## Shallow cloning is resulting in the wrong version of Salt, even with a depth of 5
+                ## getting 3007.0+0na.246d066 when it should be 3007.1+410.g246d066457, disabling for now
+                ## if git clone --depth 1 --branch "$GIT_REV" "$_SALT_REPO_URL" "$__SALT_CHECKOUT_REPONAME"; then
+                echodebug "git command, git clone --branch $GIT_REV $_SALT_REPO_URL $__SALT_CHECKOUT_REPONAME"
+                if git clone --branch "$GIT_REV" "$_SALT_REPO_URL" "$__SALT_CHECKOUT_REPONAME"; then
                     # shellcheck disable=SC2164
                     cd "${_SALT_GIT_CHECKOUT_DIR}"
                     __SHALLOW_CLONE=$BS_TRUE
+                    echoinfo  "shallow git cloned $GIT_REV, version $(python3 salt/version.py)"
```
Comment (twangboy) [inline bootstrap-salt.sh]: We're not doing a shallow clone anymore, right? Does this message need to be reworded?

File: bootstrap-salt.sh [hunk 2]
```diff
@@ -2119,10 +2125,13 @@ __git_clone_and_checkout() {
         fi
 
         if [ "$__SHALLOW_CLONE" -eq $BS_FALSE ]; then
+            echodebug "shadow clone false, BS_FALSE $BS_FALSE, git clone $_SALT_REPO_URL $__SALT_CHECKOUT_REPONAME"
```
Comment (twangboy) [inline bootstrap-salt.sh]: shadow -> shallow

**Review by twangboy — APPROVED** [review]

**Review by twangboy — APPROVED** [review]
