### PR TITLE
Ensure the REPO_ARCH for Arm64 is correct.

### LINKED ISSUE #1866: Bootstrap script assigns amd64 architecture for arm64 arch
### Description of Issue/Question

When I download and run the currently published bootstrap script from  https://bootstrap.saltstack.com the script fails to install on a EC2 instance running Ubuntu 20.04, complaining that python3-zmq can't be installed.  Inspecting the script, specifically line 1436, you can see the architecture being incorrectly set to amd64

>         "arm64")
>            if [ "$_CUSTOM_REPO_URL" != "null" ]; then
>                warn_msg="Support for arm64 is experimental, make sure the custom repository used has the expected structure and contents."
 >           else
 >               # Saltstack official repository does not yet have arm64 metadata,
 >               # use amd64 repositories on arm64, since all pkgs are arch-independent
 >               __REPO_ARCH="amd64" <---
 >               __REPO_ARCH_DEB="deb [signed-by=/usr/share/keyrings/salt-archive-keyring.gpg arch=$__REPO_ARCH]"
 >               warn_msg="Support for arm64 packages is experimental and might rely on architecture-independent packages from the amd64 repository."

### Setup
A fresh EC2 instance with Ubuntu 20.04 running on a graviton processor

### Steps to Reproduce Issue
As root on the above fresh system, run: wget -O install_salt.sh https://bootstrap.saltstack.com && sh ./install_salt.sh

### PR DESCRIPTION
**Pull request by garethgreenaway**
### What does this PR do?
Ensure the REPO_ARCH for Arm64 is correct.

### What issues does this PR fix or reference?
#1866

### CODE REVIEW

**Review by s0undt3ch — APPROVED** [review]

File: bootstrap-salt.sh [hunk 1]
```diff
@@ -1440,7 +1440,7 @@ __check_dpkg_architecture() {
             else
                 # Saltstack official repository does not yet have arm64 metadata,
                 # use amd64 repositories on arm64, since all pkgs are arch-independent
```
Comment (twangboy) [inline bootstrap-salt.sh]: Wouldn't this comment also need to change?

**Review by twangboy — CHANGES_REQUESTED** [review]

File: bootstrap-salt.sh (hunk 1 above)
Comment (garethgreenaway) [reply bootstrap-salt.sh]: Good catch.

**Review by MKLeb — APPROVED** [review]

**Review by twangboy — APPROVED** [review]
