### PR TITLE
Only install Python version if "-y" is defined

### LINKED ISSUE #1121: Errors on run if ius-release package is already installed (CentOS 6)
### Description of Issue/Question

I'm trying to restore automated Salt installation after experiencing #1115 -- currently salt-bootstrap is broken for me on CentOS 6.

In trying to workaround #1115, I followed @rallytime's suggestions to try and get things working.  What I found is that with the `-y` option enabled, if the `ius-release` package is already installed (eg I had it already or else if you'd already run salt-bootstrap), salt-bootstrap errors out at the point of checking dependencies.  

A further workaround is to use the `-r` option to disable repository checking, but this means some foreknowledge about the target system is required to decide whether or not to use that option.  

### Setup
Run the following CentOS 6.7 x86_64 VM:
```
curl -o bootstrap-salt.sh -L https://bootstrap.saltstack.com/develop
sudo sh bootstrap-salt.sh -D -P -y -x python2.7 git develop
```

### Steps to Reproduce Issue
Run the above, wait while the setup takes place and note the error at the end:
```
INFO: Cloning Salt's git repository succeeded
INFO: Attempting to install a repo to help provide a separate python package
INFO: centos
INFO: Installing IUS repo
Loaded plugins: fastestmirror
Setting up Install Process
Examining /var/tmp/yum-root-WwmIVv/ius-release.rpm: ius-release-1.0-15.ius.centos6.noarch
/var/tmp/yum-root-WwmIVv/ius-release.rpm: does not update installed package.
Error: Nothing to do
ERROR: Failed to run install_centos_git_deps()!!!
DEBUG: Cleaning up the Salt Temporary Git Repository
DEBUG: Removing the logging pipe /tmp/bootstrap-salt.logpipe
```

Running the `yum install .../ius-release.rpm` command directly return `1` so this appears to be what's being detected as an error.

### Versions and Systems

`bootstrap-salt.sh -v`
```
develop -- Version 2017.05.24
```

Adding the `-r` option to install (so that install succeeds) allows me to run `salt --versions-report`:
```
Salt Version:
           Salt: 2017.7.0-1840-g1b9cb26
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Jul 12 2017, 17:32:34)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: centos 6.7 Final
         locale: UTF-8
        machine: x86_64
        release: 2.6.32-696.6.3.el6.x86_64
         system: Linux
        version: CentOS 6.7 Final
```

### PR DESCRIPTION
**Pull request by rallytime**
### What does this PR do?
Allows the `-x` option to be used _without_ the `-y` option. This is useful in situations where the ius-community repo and related Python version is already installed, but the pip packages still need to be installed.

Previously, both the `-x` and `-y` options were both required to run the Python installation and the pip dependency installation. This PR splits out the `-y` option requirement when `-x` is passed. That way, the `-y` option can be left off if the required python version and ius repo is already installed. Note that for the `-y` option being passed, `-x` is still required.

### What issues does this PR fix or reference?
Fixes #1121

### Previous Behavior
If the IUS repo was already installed (from a previous bootstrap run, or otherwise), the bootstrap script would error out on the next run:
```
INFO: Cloning Salt's git repository succeeded
INFO: Attempting to install a repo to help provide a separate python package
INFO: centos
INFO: Installing IUS repo
Loaded plugins: fastestmirror
Setting up Install Process
Examining /var/tmp/yum-root-WwmIVv/ius-release.rpm: ius-release-1.0-15.ius.centos6.noarch
/var/tmp/yum-root-WwmIVv/ius-release.rpm: does not update installed package.
Error: Nothing to do
ERROR: Failed to run install_centos_git_deps()!!!
DEBUG: Cleaning up the Salt Temporary Git Repository
DEBUG: Removing the logging pipe /tmp/bootstrap-salt.logpipe
```

### New Behavior
The `-y` option is no longer required to trigger the pip installation using the python version defined with `-x`.

Example to install Python:
```
./bootstrap-salt.sh -y -x Python2.7 git v2017.7.0
```
Example to install pip dependencies where Python2.7 already exists on the VM:
```
./bootstrap-salt.sh -x Python2.7 git v2017.7.0
```

@Ch3LL Can you review this PR since this touches code that you added recently?

### CODE REVIEW

File: bootstrap-salt.sh [hunk 1]
```diff
@@ -3688,11 +3673,31 @@ install_centos_git_deps() {
...
+
+        if [ "$_INSTALL_CLOUD" -eq "${BS_TRUE}" ]; then
+            _PIP_PACKAGES="${_PIP_PACKAGES} apache-libcloud"
+        fi
+
+        __install_pip_pkgs "${_PIP_PACKAGES}" "${_PY_EXE}" || return 1
     else
-        # shellcheck disable=SC2086
-        __yum_install_noinput ${__PACKAGES} || return 1
+        __yum_install_noinput "${__PACKAGES}" || return 1
```
Comment (vutny) [inline bootstrap-salt.sh]: This is not gonna work, because the package list would be passed as *single* argument.
That's why we have word splitting check bypassed here.

**Review by vutny — CHANGES_REQUESTED** [review]
👍 I like the idea of installing dependencies later in appropriate functions. But, I have spot some bug 😄

File: bootstrap-salt.sh (hunk 1 above)
Comment (rallytime) [reply bootstrap-salt.sh]: Oh, yes. Good catch.

**Comment by rallytime** [comment]
@vutny Fixed.

**Review by vutny — APPROVED** [review]
LGTM

**Review by Ch3LL — APPROVED** [review]
