### PR TITLE
fix(suse): updates for opensuse tumbleweed

### LINKED ISSUE #1320: SUSE 15 doesn't work
bootstrap-salt.sh script doesn't work with SUSE 15.

Reproduce: bootstrap-salt.sh -D

### Versions and Systems
bootstrap-salt.sh -- Version 2018.08.15

### PR DESCRIPTION
**Pull request by noelmcloughlin**
### What does this PR do?

Adds support for OpenSUSE Tumbleweed

### What issues does this PR fix or reference?

It fixes  #1320  on Tumbleweed
It simplifies a case statement on Suse/SLES
It fixes following error on Tumbleweed
```
bootstrap_salt.sh: line 6382: /sbin/chkconfig: No such file or directory
bootstrap_salt.sh: line 6383: /sbin/chkconfig: No such file or directory
```
### Previous Behavior

Not working on Opensuse Tumbleweed

### New Behavior

Working on Opensuse Tumbleweed

### Provider ###

```vagrant init opensuse/Tumbleweed.x86_64```

### Versions ###
```
vagrant@localhost:~> salt-call --versions-report
Salt Version:
           Salt: 2019.2.3
 
Dependency Versions:
           cffi: 1.14.0
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.11.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.35.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: 2.20
       pycrypto: Not Installed
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.8.2 (default, Mar 05 2020, 18:58:42) [GCC]
   python-gnupg: Not Installed
         PyYAML: 5.3
          PyZMQ: 19.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.2
 
System Versions:
           dist: opensuse-tumbleweed 20200324 
         locale: utf-8
        machine: x86_64
        release: 5.5.6-1-default
         system: Linux
        version: openSUSE Tumbleweed 20200324 
```

### Log ###

```
localhost:/home/vagrant # sh bootstrap_salt.sh -x python3
 *  INFO: Running version: 2020.02.24
 *  INFO: Executed by: shell pipe
 *  INFO: Command line: 'bootstrap_salt.sh -x python3'
 *  INFO: Detected -x option. Using python3 to install Salt.

 *  INFO: System Information:
 *  INFO:   CPU:          GenuineIntel
 *  INFO:   CPU Arch:     x86_64
 *  INFO:   OS Name:      Linux
 *  INFO:   OS Version:   5.5.6-1-default
 *  INFO:   Distribution: opensuse-tumbleweed 20200324

 *  INFO: Installing minion
 *  INFO: Found function install_opensuse_stable_deps
 *  INFO: Found function config_salt
 *  INFO: Found function preseed_master
 *  INFO: Found function install_opensuse_stable
 *  INFO: Found function install_opensuse_stable_post
 *  INFO: Found function install_opensuse_restart_daemons
 *  INFO: Found function daemons_running
 *  INFO: Found function install_opensuse_check_services
 *  INFO: Running install_opensuse_stable_deps()
Adding repository 'Salt releases for SLE-based SUSE products (openSUSE_Tumbleweed)' [......done]
Repository 'Salt releases for SLE-based SUSE products (openSUSE_Tumbleweed)' successfully added

URI         : http://repo.saltstack.com/opensuse/openSUSE_Tumbleweed/
Enabled     : Yes                                                    
GPG Check   : Yes                                                    
Autorefresh : Yes                                                    
Priority    : 99 (default priority)                                  

Repository priorities are without effect. All enabled repositories share the same priority.
Repository 'openSUSE-Tumbleweed-Non-Oss' is up to date.
Repository 'openSUSE-Tumbleweed-Oss' is up to date.
Repository 'openSUSE-Tumbleweed-Update' is up to date.
Retrieving repository 'Salt releases for SLE-based SUSE products (openSUSE_Tumbleweed)' metadata [...

Automatically importing the following key:

  Repository:       Salt releases for SLE-based SUSE products (openSUSE_Tumbleweed)     
  Key Name:         systemsmanagement OBS Project <systemsmanagement@build.opensuse.org>
  Key Fingerprint:  50E60431 54485D99 0732B5D6 ACAA9CF7 E6E5A213                        
  Key Created:      Wed Jul 24 15:26:49 2019                                            
  Key Expires:      Fri Oct  1 15:26:49 2021                                            
  Rpm Name:         gpg-pubkey-e6e5a213-5d3878b9                                        


.done]
Building repository 'Salt releases for SLE-based SUSE products (openSUSE_Tumbleweed)' cache [....done]
All repositories have been refreshed.
Loading repository data...
Reading installed packages...
Package 'python-zypp' not found.
'python-PyYAML' not found in package names. Trying capabilities.
'python-requests' not found in package names. Trying capabilities.
 *  INFO: Running install_opensuse_stable()
Loading repository data...
Reading installed packages...
Resolving package dependencies...

The following 46 NEW packages are going to be installed:
  libgomp1 libpgm-5_2-0 libpython3_8-1_0 librpmbuild9 libsodium23 libunwind libyaml-0-2 libzmq5 logrotate python3 python3-Babel python3-Jinja2 python3-M2Crypto python3-MarkupSafe python3-PyYAML python3-appdirs python3-asn1crypto python3-base python3-certifi python3-cffi python3-chardet python3-cryptography python3-distro python3-idna python3-msgpack python3-ordered-set python3-packaging python3-psutil python3-py python3-pyOpenSSL python3-pyasn1 python3-pycparser python3-pyparsing python3-pytz python3-pyzmq python3-requests python3-rpm python3-salt python3-setuptools python3-simplejson python3-six python3-tornado4 python3-urllib3 python3-zypp-plugin salt salt-minion

46 new packages to install.
Overall download size: 28.6 MiB. Already cached: 0 B. After the operation, additional 132.7 MiB will be used.
Continue? [y/n/v/...? shows all options] (y): y
Retrieving package libgomp1-10.0.1+git175037-1.2.x86_64 (1/46), 126.7 KiB (336.1 KiB unpacked)
Retrieving: libgomp1-10.0.1+git175037-1.2.x86_64.rpm [.done]
Retrieving package libpgm-5_2-0-5.2.122-8.2.x86_64 (2/46), 159.2 KiB (289.8 KiB unpacked)
Retrieving: libpgm-5_2-0-5.2.122-8.2.x86_64.rpm [.done]
Retrieving package libpython3_8-1_0-3.8.2-1.4.x86_64 (3/46),   1.3 MiB (  3.5 MiB unpacked)
Retrieving: libpython3_8-1_0-3.8.2-1.4.x86_64.rpm [.......done (200.2 KiB/s)]
Retrieving package libsodium23-1.0.18-2.2.x86_64 (4/46), 164.7 KiB (363.6 KiB unpacked)
Retrieving: libsodium23-1.0.18-2.2.x86_64.rpm [.done (391.6 KiB/s)]
Retrieving package libunwind-1.3.1-2.1.x86_64 (5/46),  56.8 KiB (177.5 KiB unpacked)
Retrieving: libunwind-1.3.1-2.1.x86_64.rpm [.done (248.8 KiB/s)]
Retrieving package libyaml-0-2-0.2.2-2.1.x86_64 (6/46),  53.9 KiB (126.3 KiB unpacked)
Retrieving: libyaml-0-2-0.2.2-2.1.x86_64.rpm [done]
Retrieving package logrotate-3.16.0-1.1.x86_64 (7/46),  75.1 KiB (156.2 KiB unpacked)
Retrieving: logrotate-3.16.0-1.1.x86_64.rpm [.done (488.1 KiB/s)]
Retrieving package librpmbuild9-4.15.1-3.1.x86_64 (8/46), 165.5 KiB (181.7 KiB unpacked)
Retrieving: librpmbuild9-4.15.1-3.1.x86_64.rpm [.done (153.9 KiB/s)]
Retrieving package python3-base-3.8.2-1.4.x86_64 (9/46),   8.1 MiB ( 32.9 MiB unpacked)
Retrieving: python3-base-3.8.2-1.4.x86_64.rpm [...........................done (312.9 KiB/s)]
Retrieving package libzmq5-4.3.2-1.2.x86_64 (10/46), 198.9 KiB (538.5 KiB unpacked)
Retrieving: libzmq5-4.3.2-1.2.x86_64.rpm [.done (473.6 KiB/s)]
Retrieving package python3-3.8.2-1.1.x86_64 (11/46),  80.5 KiB (168.6 KiB unpacked)
Retrieving: python3-3.8.2-1.1.x86_64.rpm [done]
Retrieving package python3-zypp-plugin-0.6.3-3.5.noarch (12/46),  12.9 KiB ( 13.3 KiB unpacked)
Retrieving: python3-zypp-plugin-0.6.3-3.5.noarch.rpm [.done (10.6 KiB/s)]
Retrieving package python3-six-1.14.0-3.1.noarch (13/46),  39.4 KiB ( 99.0 KiB unpacked)
Retrieving: python3-six-1.14.0-3.1.noarch.rpm [done]
Retrieving package python3-simplejson-3.17.0-1.2.x86_64 (14/46),  82.0 KiB (282.1 KiB unpacked)
Retrieving: python3-simplejson-3.17.0-1.2.x86_64.rpm [.done (236.4 KiB/s)]
Retrieving package python3-pytz-2019.3-1.2.noarch (15/46),  56.1 KiB (241.4 KiB unpacked)
Retrieving: python3-pytz-2019.3-1.2.noarch.rpm [done]
Retrieving package python3-pyparsing-2.4.6-1.2.noarch (16/46), 194.0 KiB (870.3 KiB unpacked)
Retrieving: python3-pyparsing-2.4.6-1.2.noarch.rpm [..done (319.4 KiB/s)]
Retrieving package python3-pycparser-2.20-1.1.noarch (17/46), 214.2 KiB (  1.3 MiB unpacked)
Retrieving: python3-pycparser-2.20-1.1.noarch.rpm [...done (306.3 KiB/s)]
Retrieving package python3-pyasn1-0.4.8-1.2.noarch (18/46), 167.6 KiB (919.3 KiB unpacked)
Retrieving: python3-pyasn1-0.4.8-1.2.noarch.rpm [..done (400.7 KiB/s)]
Retrieving package python3-py-1.8.1-1.2.noarch (19/46), 178.1 KiB (740.4 KiB unpacked)
Retrieving: python3-py-1.8.1-1.2.noarch.rpm [..done (304.1 KiB/s)]
Retrieving package python3-psutil-5.6.7-2.2.x86_64 (20/46), 265.8 KiB (  1.2 MiB unpacked)
Retrieving: python3-psutil-5.6.7-2.2.x86_64.rpm [.....done (252.8 KiB/s)]
Retrieving package python3-ordered-set-3.1.1-3.2.noarch (21/46),  19.4 KiB ( 42.5 KiB unpacked)
Retrieving: python3-ordered-set-3.1.1-3.2.noarch.rpm [..done]
Retrieving package python3-msgpack-0.6.2-1.2.x86_64 (22/46),  91.8 KiB (284.5 KiB unpacked)
Retrieving: python3-msgpack-0.6.2-1.2.x86_64.rpm [.done (167.2 KiB/s)]
Retrieving package python3-idna-2.9-1.1.noarch (23/46),  79.6 KiB (693.5 KiB unpacked)
Retrieving: python3-idna-2.9-1.1.noarch.rpm [.done (343.7 KiB/s)]
Retrieving package python3-distro-1.4.0-1.4.noarch (24/46),  34.5 KiB (150.1 KiB unpacked)
Retrieving: python3-distro-1.4.0-1.4.noarch.rpm [.done]
Retrieving package python3-chardet-3.0.4-8.2.noarch (25/46), 170.6 KiB (967.8 KiB unpacked)
Retrieving: python3-chardet-3.0.4-8.2.noarch.rpm [..done (397.2 KiB/s)]
Retrieving package python3-certifi-2019.11.28-1.2.noarch (26/46),  16.4 KiB (  7.0 KiB unpacked)
Retrieving: python3-certifi-2019.11.28-1.2.noarch.rpm [done]
Retrieving package python3-asn1crypto-1.3.0-1.2.noarch (27/46), 182.3 KiB (  1.2 MiB unpacked)
Retrieving: python3-asn1crypto-1.3.0-1.2.noarch.rpm [..done (358.9 KiB/s)]
Retrieving package python3-appdirs-1.4.3-5.2.noarch (28/46),  23.3 KiB ( 83.1 KiB unpacked)
Retrieving: python3-appdirs-1.4.3-5.2.noarch.rpm [done]
Retrieving package python3-PyYAML-5.3-1.2.x86_64 (29/46), 195.4 KiB (758.0 KiB unpacked)
Retrieving: python3-PyYAML-5.3-1.2.x86_64.rpm [...done (318.6 KiB/s)]
Retrieving package python3-MarkupSafe-1.1.1-1.5.x86_64 (30/46),  32.4 KiB ( 79.9 KiB unpacked)
Retrieving: python3-MarkupSafe-1.1.1-1.5.x86_64.rpm [...done (62.3 KiB/s)]
Retrieving package python3-M2Crypto-0.35.2-2.1.x86_64 (31/46), 268.9 KiB (  1.4 MiB unpacked)
Retrieving: python3-M2Crypto-0.35.2-2.1.x86_64.rpm [............done (67.3 KiB/s)]
Retrieving package python3-tornado4-4.5.3-3.2.x86_64 (32/46), 419.1 KiB (  2.4 MiB unpacked)
Retrieving: python3-tornado4-4.5.3-3.2.x86_64.rpm [.......done (168.7 KiB/s)]
Retrieving package python3-Babel-2.8.0-1.2.noarch (33/46),   5.0 MiB ( 26.4 MiB unpacked)
Retrieving: python3-Babel-2.8.0-1.2.noarch.rpm [...................done (295.4 KiB/s)]
Retrieving package python3-packaging-20.1-1.2.noarch (34/46),  67.5 KiB (262.2 KiB unpacked)
Retrieving: python3-packaging-20.1-1.2.noarch.rpm [.done (219.4 KiB/s)]
Retrieving package python3-cffi-1.14.0-1.3.x86_64 (35/46), 313.0 KiB (  1.2 MiB unpacked)
Retrieving: python3-cffi-1.14.0-1.3.x86_64.rpm [....done (251.3 KiB/s)]
Retrieving package python3-Jinja2-2.11.1-1.2.noarch (36/46), 246.1 KiB (  1.2 MiB unpacked)
Retrieving: python3-Jinja2-2.11.1-1.2.noarch.rpm [.done (334.3 KiB/s)]
Retrieving package python3-setuptools-44.0.0-1.2.noarch (37/46), 671.1 KiB (  3.5 MiB unpacked)
Retrieving: python3-setuptools-44.0.0-1.2.noarch.rpm [....done (303.3 KiB/s)]
Retrieving package python3-pyzmq-19.0.0-1.1.x86_64 (38/46), 523.9 KiB (  2.3 MiB unpacked)
Retrieving: python3-pyzmq-19.0.0-1.1.x86_64.rpm [...done (392.7 KiB/s)]
Retrieving package python3-cryptography-2.8-1.4.x86_64 (39/46), 430.2 KiB (  2.6 MiB unpacked)
Retrieving: python3-cryptography-2.8-1.4.x86_64.rpm [....done (268.9 KiB/s)]
Retrieving package python3-pyOpenSSL-19.1.0-1.2.noarch (40/46), 110.5 KiB (576.9 KiB unpacked)
Retrieving: python3-pyOpenSSL-19.1.0-1.2.noarch.rpm [.done (124.0 KiB/s)]
Retrieving package python3-urllib3-1.25.8-1.2.noarch (41/46), 195.0 KiB (644.9 KiB unpacked)
Retrieving: python3-urllib3-1.25.8-1.2.noarch.rpm [..done (359.5 KiB/s)]
Retrieving package python3-requests-2.23.0-1.2.noarch (42/46), 159.4 KiB (495.8 KiB unpacked)
Retrieving: python3-requests-2.23.0-1.2.noarch.rpm [....done (196.0 KiB/s)]
Retrieving package python3-rpm-4.15.1-5.1.x86_64 (43/46),  60.5 KiB (214.7 KiB unpacked)
Retrieving: python3-rpm-4.15.1-5.1.x86_64.rpm [..done (75.6 KiB/s)]
Retrieving package python3-salt-2019.2.3-2.1.x86_64 (44/46),   7.5 MiB ( 40.9 MiB unpacked)
Retrieving: python3-salt-2019.2.3-2.1.x86_64.rpm [.....................................done (219.7 KiB/s)]
Retrieving package salt-2019.2.3-2.1.x86_64 (45/46),  73.0 KiB ( 28.5 KiB unpacked)
Retrieving: salt-2019.2.3-2.1.x86_64.rpm [.done]
Retrieving package salt-minion-2019.2.3-2.1.x86_64 (46/46), 166.2 KiB ( 40.2 KiB unpacked)
Retrieving: salt-minion-2019.2.3-2.1.x86_64.rpm [..done (350.7 KiB/s)]

Checking for file conflicts: [.........done]
( 1/46) Installing: libgomp1-10.0.1+git175037-1.2.x86_64 [.........done]
( 2/46) Installing: libpgm-5_2-0-5.2.122-8.2.x86_64 [............done]
( 3/46) Installing: libpython3_8-1_0-3.8.2-1.4.x86_64 [............done]
( 4/46) Installing: libsodium23-1.0.18-2.2.x86_64 [.........done]
( 5/46) Installing: libunwind-1.3.1-2.1.x86_64 [.........done]
( 6/46) Installing: libyaml-0-2-0.2.2-2.1.x86_64 [.......done]
( 7/46) Installing: logrotate-3.16.0-1.1.x86_64 [.........done]
Additional rpm output:
Created symlink /etc/systemd/system/timers.target.wants/logrotate.timer -> /usr/lib/systemd/system/logrotate.timer.


( 8/46) Installing: librpmbuild9-4.15.1-3.1.x86_64 [.........done]
( 9/46) Installing: python3-base-3.8.2-1.4.x86_64 [............done]
(10/46) Installing: libzmq5-4.3.2-1.2.x86_64 [...........done]
(11/46) Installing: python3-3.8.2-1.1.x86_64 [........done]
(12/46) Installing: python3-zypp-plugin-0.6.3-3.5.noarch [.......done]
(13/46) Installing: python3-six-1.14.0-3.1.noarch [.......done]
(14/46) Installing: python3-simplejson-3.17.0-1.2.x86_64 [...........done]
(15/46) Installing: python3-pytz-2019.3-1.2.noarch [..........done]
(16/46) Installing: python3-pyparsing-2.4.6-1.2.noarch [............done]
(17/46) Installing: python3-pycparser-2.20-1.1.noarch [............done]
(18/46) Installing: python3-pyasn1-0.4.8-1.2.noarch [............done]
(19/46) Installing: python3-py-1.8.1-1.2.noarch [............done]
(20/46) Installing: python3-psutil-5.6.7-2.2.x86_64 [............done]
(21/46) Installing: python3-ordered-set-3.1.1-3.2.noarch [.......done]
(22/46) Installing: python3-msgpack-0.6.2-1.2.x86_64 [...........done]
(23/46) Installing: python3-idna-2.9-1.1.noarch [............done]
(24/46) Installing: python3-distro-1.4.0-1.4.noarch [........done]
(25/46) Installing: python3-chardet-3.0.4-8.2.noarch [............done]
Additional rpm output:
update-alternatives: using /usr/bin/chardetect-3.8 to provide /usr/bin/chardetect (chardetect) in auto mode


(26/46) Installing: python3-certifi-2019.11.28-1.2.noarch [..........done]
(27/46) Installing: python3-asn1crypto-1.3.0-1.2.noarch [............done]
(28/46) Installing: python3-appdirs-1.4.3-5.2.noarch [.......done]
(29/46) Installing: python3-PyYAML-5.3-1.2.x86_64 [............done]
(30/46) Installing: python3-MarkupSafe-1.1.1-1.5.x86_64 [...........done]
(31/46) Installing: python3-M2Crypto-0.35.2-2.1.x86_64 [............done]
(32/46) Installing: python3-tornado4-4.5.3-3.2.x86_64 [............done]
(33/46) Installing: python3-Babel-2.8.0-1.2.noarch [............done]
Additional rpm output:
update-alternatives: using /usr/bin/pybabel-3.8 to provide /usr/bin/pybabel (pybabel) in auto mode


(34/46) Installing: python3-packaging-20.1-1.2.noarch [..........done]
(35/46) Installing: python3-cffi-1.14.0-1.3.x86_64 [............done]
(36/46) Installing: python3-Jinja2-2.11.1-1.2.noarch [............done]
(37/46) Installing: python3-setuptools-44.0.0-1.2.noarch [............done]
Additional rpm output:
update-alternatives: using /usr/bin/easy_install-3.8 to provide /usr/bin/easy_install (easy_install) in auto mode


(38/46) Installing: python3-pyzmq-19.0.0-1.1.x86_64 [............done]
(39/46) Installing: python3-cryptography-2.8-1.4.x86_64 [............done]
(40/46) Installing: python3-pyOpenSSL-19.1.0-1.2.noarch [...........done]
(41/46) Installing: python3-urllib3-1.25.8-1.2.noarch [............done]
(42/46) Installing: python3-requests-2.23.0-1.2.noarch [............done]
(43/46) Installing: python3-rpm-4.15.1-5.1.x86_64 [..........done]
(44/46) Installing: python3-salt-2019.2.3-2.1.x86_64 [............done]
(45/46) Installing: salt-2019.2.3-2.1.x86_64 [..........done]
(46/46) Installing: salt-minion-2019.2.3-2.1.x86_64 [......done]
Executing %posttrans script 'python3-salt-2019.2.3-2.1.x86_64.rpm' [....done]
 *  INFO: Running install_opensuse_stable_post()
bootstrap_salt.sh: line 6382: /sbin/chkconfig: No such file or directory
bootstrap_salt.sh: line 6383: /sbin/chkconfig: No such file or directory
 *  INFO: Running install_opensuse_check_services()
 *  INFO: Running install_opensuse_restart_daemons()
 *  INFO: Running daemons_running()
 *  INFO: Salt installed!
```

### CODE REVIEW

**Comment by noelmcloughlin** [comment]
The failed CI/CD test for Ubuntu 16.04 is unrelated to this PR. 

(That's some kitchen issue: https://github.com/test-kitchen/kitchen-vagrant/issues/115)

File: bootstrap-salt.sh [hunk 1]
```diff
@@ -996,7 +996,8 @@ __gather_linux_system_info() {
             # Skip setting DISTRO_NAME this time, splitting CamelCase has failed.
             # See https://github.com/saltstack/salt-bootstrap/issues/918
             [ "$n" = "$DISTRO_NAME" ] && DISTRO_NAME="" || DISTRO_NAME="$n"
-        elif [ "${DISTRO_NAME}" = "openSUSE project" ]; then
+        elif [ "$( echo "${DISTRO_NAME}" | grep openSUSE )" != "" ]; then
```
Comment (bryceml) [inline bootstrap-salt.sh:999]: this could be a bit prettier with something like
```bash
elif echo "${DISTRO_NAME}"|grep -q ^openSUSE; then
```
in my opinion

It looks like your change's style has been used elsewhere in this script though.

Comment (noelmcloughlin) [reply bootstrap-salt.sh:999]: I agree your suggestion is cleaner but ...
In this PR the conditional (line 999) now follows the same style as most other conditionals. 
https://github.com/saltstack/salt-bootstrap/blob/fbe3759e4f750aa59c0edb628b4dcb3e74f836c3/bootstrap-salt.sh#L993
The dilemma is that I should, in the first instance, follow the same style as code around the update.  
So best to keep your suggestion for separate PR.

Comment (bryceml) [reply bootstrap-salt.sh:999]: I agree, I didn't realize how much much that style was used around it until after I commented.

Comment (noelmcloughlin) [reply bootstrap-salt.sh:999]: Yes, in my original update I done something else but then noticed the style.

**Comment by bryceml** [comment]
running the pipeline locally via drone-cli seems to work with ubuntu 16.04, so I'm not sure what's up with the drone run on this pr, I can try re-running it if you want.

**Comment by noelmcloughlin** [comment]
> I'm not sure what's up with the drone run on this pr

There are two other PRs with issues too. I quickly checked drone logs and ssh connection failed, so I assumed its some problem with kitchen-vagrant, and a retry will probably fail.  Looks like a CI/CD issue on this repo?

**Comment by bryceml** [comment]
> > I'm not sure what's up with the drone run on this pr
> 
> There are two other PRs with issues too. I quickly checked drone logs and ssh connection failed, so I assumed its some problem with kitchen-vagrant, and a retry will probably fail. Looks like a CI/CD issue on this repo?

yeah, my guess is some kind of drone configuration issue.  I'll re-run it, I'll see what I can figure out.

**Review by s0undt3ch — APPROVED** [review]
